// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWD8aOMhUwZ6E3ls5Nn_xnqVBAj0QN90',
    appId: '1:1050631469935:web:261a67be8994339bf8469a',
    messagingSenderId: '1050631469935',
    projectId: 'my-experimental-notes',
    authDomain: 'my-experimental-notes.firebaseapp.com',
    storageBucket: 'my-experimental-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzegJRzQEIvhfUTYGypl-v_SiaDcEczf4',
    appId: '1:1050631469935:android:a0a66208c14291c7f8469a',
    messagingSenderId: '1050631469935',
    projectId: 'my-experimental-notes',
    storageBucket: 'my-experimental-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhrOrMU_ER0HCwVHdN42-ec2oYFoY4fg',
    appId: '1:1050631469935:ios:4f376712c8037087f8469a',
    messagingSenderId: '1050631469935',
    projectId: 'my-experimental-notes',
    storageBucket: 'my-experimental-notes.appspot.com',
    iosClientId: '1050631469935-eq5f0fbhhhocvm06r32briqvpi1plj78.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMhrOrMU_ER0HCwVHdN42-ec2oYFoY4fg',
    appId: '1:1050631469935:ios:a19ac547fbbe2e8cf8469a',
    messagingSenderId: '1050631469935',
    projectId: 'my-experimental-notes',
    storageBucket: 'my-experimental-notes.appspot.com',
    iosClientId: '1050631469935-88brdqj1b4mu69inohbg9qne816f8f5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
